### ISSUE TITLE
The Monad.Reader Issue 23

### ISSUE THREAD

**Issue by Javran** [CNMDR3G/CNMDR3G#1]
[地址](https://themonadreader.wordpress.com/2014/04/23/issue-23/)

一共五篇,选择你最想阅读的几篇,然后在回复里说一下即可(只是做个统计,不需要理由).

取决于有多少人参与,以后可能改变survey的形式吧.

现阶段暂时不知道多少人会参与进来,觉得差不多了我就close issue然后开始阅读和讨论吧 xD

更新: 参与人数比我一开始想像的多,谢谢大家的参与和兹磁 :)
- 投票截止: 北京时间 3月6日 4:00(早上)

暂时的想法是选择得票最多的两三篇,按得票降序.周期wiki里已经写了,大概一两周集中读一篇吧.
希望一周中有个大部分人都有空的时间集中讨论,关于这些话题将另开issue.
## Editorial

_by Edward Z. Yang (ezyang@cs.stanford.edu)_

This issue’s Monad Reader clocks a record page count, with over a
hundred pages of Haskell goodness from nine authors. Given that there’s
so much; I thought this issue’s editorial would be best devoted to
giving teasers for each of the articles herewithin.
-   Ever wanted to solve a programming interview question by writing a
  domain-specific language on the fly? In **FizzBuzz in Haskell**,
  Maciej takes a whimsical look at the classic interview question,
  dancing through syntax, semantics and algebraic transformations to
  arrive at a solution that would be called elegant by most people.
-   Ilya and Dimitur write in with a somewhat apologetic but very
  interesting tutorial about **Supercompilation**, a whole-program
  transformation technique. It is a nice introduction to the subject,
  and comes with running code to boot.
-   In a break from the usual uses of Haskell, Henrik, Daniel and Mikael
  describe **Haskell sound specification DSL** used in service of a
  live action role-playing game situated in the Battlestar Galactica
  universe.
-   Alberto talks about his web framework, **MFlow**, which provides a
  continuation-like method of structuring web applications, without
  actually opening the can of worms that is explicitly serializing
  continuations.
-   And last but not least, Neil offers a gentle introduction to
  **Practical Type System Benefits**, giving a taster of some of the
  more intermediate features of Haskell, including generic
  programming, parallelism, newtypes, quasiquoting and lightweight
  contracts.

Take a look!

**Comment by seckcoder** [comment]
FizzBuzz in Haskell by Embedding a Domain-Specific Language by Maciej Pírog

**Comment by fishtreesugar** [comment]
- MFlow, a continuation-based web framework without continuations
- Practical Type System Benefits

**Comment by scturtle** [comment]
Supercompilation

**Comment by shouya** [comment]
- Supercompilation
- Practical Type System Benefits

**Comment by Javran** [comment]
- fizzbuzz
- supercompilation

**Comment by objmagic** [comment]
- Practical Type System Benefits

**Comment by ranlei** [comment]
Practical Type System Benefits 
 FizzBuzz

**Comment by Javran** [comment]
确认投票截止: 北京时间 3月6日 4:00(早上)

**Comment by rink1969** [comment]
supercompilation
fizzbuzz

**Comment by Javran** [comment]
统计:

| - | - |
| --- | --- |
| FizzBuzz | 4 |
| Supercompilation | 4 |
| Practical Type System Benefits | 4 |
| MFlow | 1 |

有三个票数一样多的,不知各位对顺序有什么想法,个人偏向按issue中文章的顺序来.
确定顺序的目的是让在接下来的一两周内大家集中阅读同一篇,一起讨论交流.

再留24小时商量一下顺序,欢迎踊跃讨论.

另:欢迎大家加入freenode的 `#haskell-cn` 参与讨论.我大部分时间在线.
分享一个网页版客户端: [link](http://webchat.freenode.net/)
Nickname随意,Channels填`#haskell-cn`,其他的不用勾.

**Comment by shouya** [comment]
我覺得順序的話，practical type system benefits 或者 fizzbuzz 先來都可以，前者看起來比較 general，後者應該相對容易一點。我覺得先從簡單的開始是不錯的主意。至於 supercompilation 的話可以等下週或者下下週再讀。大家怎麼看？

另外，freenode 的 `#haskell-cn` 頻道的話，我和 javran 會盡可能長期在線的，如果有特別要我和 javran 注意的話請 reply，討論的話我們暫定在 `#haskell-cn` 頻道上進行，我跑了一個 lambdabot 在這個頻道上（目前功能還沒辦法全開不過接下來會想辦法搞定），這樣也能方便大家交流，順便把 `#haskell-cn` 這個長時間沒甚麼人的頻道稍微利用起來，我覺得也是不錯的。

希望大家感覺自由提出任何想法或者意見～

**Comment by sky7drake** [comment]
支持fizzbuzz先来，理由同上

**Comment by Javran** [comment]
目前按照大家的建议,顺序暂定: fizzbuzz, practical type system benefits, supercompilation.

另 @freizl 刚才在IRC上投了 fizzbuzz 与 MFlow

**Comment by Javran** [comment]
就按这个顺序来吧:
- FizzBuzz
- Practical Type System Benefits
- Supercompilation

因为也有人提到MFlow, 到时候看情况好了.

接下来的一周希望大家抽出一些时间阅读FizzBuzz(一周抽个一两小时有个印象就好),
然后我们约定一个时间来一起讨论 (暂定使用IRC).
为了照顾无法参加讨论的同学,我们会把讨论摘要一些放到wiki或者repo里.

补充几点:
- 我们不要求一定要把文章理解到什么程度,只要有阅读过,有个印象即可.
- 如果知道自己到底在哪个地方迷失了那更好,届时欢迎开issue提出问题.
- 平时也可以来`#haskell-cn`做客,主频道把 lambdabot 分享过来了大家随意玩 xD

Happy reading!
