### ISSUE TITLE
#haskell-cn 频道日志

### ISSUE THREAD

**Issue by Javran** [CNMDR3G/CNMDR3G#10]
计划弄个bot省得每次贴聊天记录

有空调查了一下,目前的想法是这么搞:
- [x] IRC bot 用来监视频道
- [ ] 搭个[ircbrowse](https://github.com/chrisdone/ircbrowse)
- [ ] ~~或许IRC bot直接show给ircbrowse去read最简单粗暴~~ 格式化 IRC bot 的日志输出,语法暂时没找到,
  或许只能参考[clogparse](https://hackage.haskell.org/package/clogparse)的代码. (需要这么做主要是因为ircbrowse用的是clogparse )

求熟悉这方面操作的同学提供一下技术支持/一起来折腾.

有其他想法欢迎跟贴.

**Comment by freizl** [comment]
+1 ircbrowse.
能申请直接加到 http://ircbrowse.net/ ？

**Comment by Javran** [comment]
@freizl 我也觉得能直接用的话最好,发了封邮件去问,看怎么回复了.

**Comment by Javran** [comment]
看来可能不需要我们自己搞了, Chris Done回说没问题可以加进去.

**Comment by freizl** [comment]
:+1:

**Comment by Javran** [comment]
there we go: [haskell-cn](http://ircbrowse.net/browse/haskell-cn) 
enjoy!

**Comment by Javran** [comment]
哦对, @freizl 你可以把日志的地址加在#haskell-cn的topic里..

**Comment by freizl** [comment]
nice. letme try to contact creator. i got no permission now.

**Comment by Javran** [comment]
@freizl 你刚才没设置上,`/topic` 被解释成发送的消息了,你试试给`ChanServ`发 `OP #haskell-cn haisheng` 应该就有权限了.

**Comment by freizl** [comment]
谢谢提醒，改好了。

```
/msg ChanServ TOPIC #haskell-cn Haskell中文频道 | 中文官网:http://www.haskellcn.org/ | 官网:http://haskell.org | 推荐图书: Real World Haskell <http://book.realworldhaskell.org/>， Learn You a Haskell for Great Good http://learnyouahaskell.com/ | 只有多写才能学好 Haskell | 聊天记录:http://ircbrowse.net/browse/haskell-cn
```

**Comment by Javran** [comment]
@freizl thanks!
