### ISSUE TITLE
第五次线上讨论!

### ISSUE THREAD

**Issue by Javran** [CNMDR3G/CNMDR3G#12]
按照之前投票调查的[结果](https://www.surveymonkey.com/results/SM-FKSXNZQ9/)来看,下一篇将是对[MFlow](https://themonadreader.files.wordpress.com/2014/04/mflow.pdf)的讨论. 依旧请大家尽力阅读,鼓励大家有不理解的地方不用耗大量时间去google答案.直接在这里开issue讨论或许更针对问题.

暂定4月29日至5月9日某一天举办线上讨论, 依旧请大家[点击这个链接](http://www.when2meet.com/?3046751-KjQpl)填写自己方便的时间.若不清楚如何操作请阅读[本文](https://github.com/CNMDR3G/CNMDR3G/wiki/%E5%B0%8F%E7%BB%84%E7%BA%BF%E4%B8%8A%E8%AE%A8%E8%AE%BA%E7%9B%B8%E5%85%B3).

届时将以 freenode 上的 `#haskell-cn` 频道作为讨论平台,关于如何参与讨论,具体事项参见[链接](https://github.com/CNMDR3G/CNMDR3G/wiki#%E5%A6%82%E4%BD%95%E5%8F%82%E4%B8%8E).

有任何不明白的地方可以在本issue留言,谢谢大家.

P.S.

依照前几次线上讨论的数据来看,似乎时间都在周五和周六中午,你们觉得是否可以就把这时间固定下来了呢?

**Comment by Javran** [comment]
另:

前几次试着分出了一些线上讨论时间给自由讨论,
感觉效果还行,关于今后是否也这么搞想听听大家的意见,
就不另开issue了,也欢迎大家在此跟进讨论.

**Comment by shouya** [comment]
自由討論茲磁啊～

**Comment by shouya** [comment]
時間就定在北京時間每週六的 10:30 到 13:30，以後每週的都固定在這個時間。

我的想法是僅可能每週都能進行一些 Monad Reader 雜誌閱讀討論，常規是每週一篇，在文章太長或者適合更多深究的情況可以分多週來討論同一篇。然後每次線上討論最好能留至少一個小時給大家自由討論。

另外就是僅可能每篇文章能留給大家至少一週的時間來閱讀，如果時間太倉促就只進行非正式的線上討論好了。每週的閱讀的文章將會同時更新在 CNMDR3G 的首頁 README 上。

謝謝大家茲磁～大白兔希望聽到大家的想法，也不知道是想表达一种怎样的思想感情。

**Comment by Javran** [comment]
表示差不多一个意思. 我目前的计划:
- 每篇的讨论最多花两周时间
- 取决于讨论的进度,每周安排自由讨论的时间

另,在公共频道请适度讨论白学,谢谢.

**Comment by freizl** [comment]
白学 ?

**Comment by rink1969** [comment]
本周六是五一假期
可能要出去玩。。。

**Comment by Javran** [comment]
@freizl 不用在意,白学就是提及大白兔的句子,和讨论无关可以忽略...

@rink1969 哦对...已然忘记了,这么说来这周可能无法常规时间了吧..?

**Comment by Javran** [comment]
额感觉填的人不多不过每次都能来点人,这样吧,还是老时间..

北京时间 5月2日 10:00-13:00 线上讨论, 内容为MFlow, 最后一个小时安排自由讨论~

若时间安排上有建议欢迎私信/回复.

**Comment by ninegua** [comment]
和前几次一样，我只能赶上最后的半小时到一小时。不过没有关系，我先把我读了这篇文章后的想法提一下。
1. 整个文章感觉写得不是特别好，重点似乎是在说 (a) RESTful 的架构好是好，但程序不好维护 (b) 好维护的程序需要处理中间状态 (c) 单靠依赖客户端存储中间状态是不够的 (d) 依靠 log replay input 是个办法，但是每次都 replay 有点多余 (e) timeout 的做法是个折中 (f) 各种使用 MFlow 的方案。基本上到 (e) 之后我就觉得 lost 了，剩下的部分和前面结合不起来，而且 horizontal scale out 的解决方案完全没有展开讲。
2. 文章里基于 log 的模型还有 playback，这不就这两年越来越火的 kafka 所鼓吹的么，看[这篇文章](http://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying)有比较深入的架构介绍。 
3. 第 6 页的 BackT 类型，是一个真正的 Monad 吗（是否满足 monad laws）？直觉上我有点怀疑

**Comment by Javran** [comment]
感谢大家参与这次的讨论,聊天记录[参见这里](http://ircbrowse.net/browse/haskell-cn?events_page=42)

下次将进入Issue 22话题的讨论.

**Comment by Javran** [comment]
过期关闭.
