### ISSUE TITLE
FizzBuzz: 分享一个解法

### ISSUE THREAD

**Issue by Javran** [CNMDR3G/CNMDR3G#2]
一开始叫我读FizzBuzz我是拒绝的,因为你不能叫我读我就读,首先我要试一下

所以暂时没读多少的情况下,先琢磨出了个解法.抛砖引玉吧.

这个题看起来像MonadPlus能干的事情,不过事实上不是...

因为MonadPlus中一旦有一个地方计算失败了,后续的计算都被取消了.

所以我对MonadPlus做了一点"hack", 以下代码的关键在于`amend`和`unamend`.

`amend oops m` 的意思是,如果`m`失败了,那么就加个特技`oops`上去,好让后面的计算能接着跑

`unamend oops (amend oops m) = m`, 换句话说`unamend oops`取消了`amend oops`的效果.

`oops` 需要取一个在计算成功的情况下不可能得到的值,这样`unamend`才能正确把这个值从结果里移除. 所以这个地方直接让`oops = []`.

``` haskell
module FizzBuzz where

import Prelude hiding (mapM_,concat,product)
import Control.Monad hiding (mapM_)
import Data.Foldable

keepInput :: (a -> b) -> a -> (b,a)
keepInput f x = (f x, x)

fizzbuzz :: Int -> String
fizzbuzz n = head $ amend (show n) divisible
  where
    -- invariant: length (amend _ _) /= 0
    amend oops m = m `mplus` [ oops ]
    unamend oops = filter (/= oops)
    fb = concat (foldMap (amend [])
                         [ ["fizz" | test  3]
                         , ["buzz" | test  5]
                         , ["hiss" | test  7]
                         , ["howl" | test 11]
                         ])
    divisible = unamend [] (return fb)
    test x = n `mod` x == 0

main :: IO ()
main = mapM_ (print . keepInput fizzbuzz)
             [1.. product [3,5,7,11]]
```

欢迎各种吐槽!

**Comment by scturtle** [comment]
>  因为MonadPlus中一旦有一个地方计算失败了,后续的计算都被取消了.

MonadPlus 是个好主意！不过这句话不敢苟同。我看来 MonadPlus 恰恰是组合不同 context 下的计算结果，而恰好 Maybe 和 Either 的实现是取第一个结果。对于这个问题，显然 List/String 比较合适。既然大家不是搞娱乐的那就再吐槽一下，我觉得写成这个样子的 haskell 实在是不具可读性，还不如 for 循环。也上一个版本供吐槽（concat 就是 List/String 的 msum）：

``` haskell
tests :: [Int -> String]
tests = [\x -> if x `rem` n == 0 then result else ""
        |(n, result) <- [(3, "fizz"), (5, "buzz")
                        ,(7, "hiss"), (11, "howl")]]

fizzBuzz' :: Int -> String
fizzBuzz' n =
  case concat [f n | f <- tests] of
    "" -> show n
    word -> word
```

**Comment by Javran** [comment]
赞! 不过看了你的代码我反而觉得自己太纠结于MonadPlus了,实际上没有必要,
你的代码确实可读性也很高.

> MonadPlus 是个好主意！不过这句话不敢苟同。我看来 MonadPlus 恰恰是组合不同 context 下的计算结果，而恰好 Maybe 和 Either 的实现是取第一个结果。

这里我想稍微解释一下自己的理解方式:

我描述的是`mzero`的性质.在 [MonadPlus](http://hackage.haskell.org/package/base/docs/Control-Monad.html#t:MonadPlus) 的文档中:

``` haskell
-- | Monads that also support choice and failure.
class Monad m => MonadPlus m where
   -- | the identity of 'mplus'.  It should also satisfy the equations
   --
   -- > mzero >>= f  =  mzero
   -- > v >> mzero   =  mzero
   --
   mzero :: m a 
   -- | an associative operation
   mplus :: m a -> m a -> m a
```

在do notation中,`mzero`之后出现的代码确实是不会被执行的. 你指的"组合结果"应该指的是这里的`mplus`.

有意思的是MonadPlus并没有对`mplus`做太多的限制 -- 唯一的限制是`mzero`要是`mplus`的零元,
所以这也就暗示了多种实现方式的可能: right-biased Maybe或者限制结果个数的List按道理都是可以实现的.或许对List定义一个新的MonadPlus实现也可以解决这个问题也说不定.

P.S.稍微读了下文章觉得这或许是continuation monad的好例子,有空了再稍微研究下好了.

**Comment by shouya** [comment]
讚～

我也來一個～如果把 `(Int, String)` 的組合用半群來抽象就可以方便生成一個無限長的 list，然後 query 指定元素就可以了，上代碼：

``` haskell
{-# LANGUAGE FlexibleInstances #-}
import Data.Maybe (fromMaybe)

class Semigroup a where
  (<>) :: a -> a -> a

instance Semigroup (Int, String) where
  (n1,s1) <> (n2,s2) = (n1 * n2, s1 ++ s2)

fizzSeq :: [(Int, String)]
fizzSeq = (3, "fizz"):(5, "buzz"):(7, "hiss"):(11, "howl"):
          [x <> y | x <- fizzSeq, y <- fizzSeq]

fizzbuzz'' n = fromMaybe "" $ lookup n fizzSeq
```

這個方案的話其實效率不高，`fizzbuzz'' n` 因為要搜尋（順便 construct）列表所以是 O(n)，雖然不實用不過拿來玩還是可以的～

UPDATE: @Javran 提到了 data-ordlist 這個庫，對於 ordered list 做 union 似乎很方便。我沒有瞭解過，不過從用法大概猜到工作方式，

``` haskell
[3,6..] `union` [5,10,...] `union` [7,14,..]
```

所以我的方法用其 `union` 函數的話大概可以這麼寫，應該比無窮列表推導清楚很多：

``` haskell
scanl (<>) (3, "fizz") `union`
scanl (<>) (5, "buzz") `union`
scanl (<>) (7, "hiss") `union`
scanl (<>) (11, "howl")

-- Simplified:
unionAll [map (scanl (<>)) [(3, "fizz"), (5, "buzz"), (7, "hiss"), (11, "howl")]]
```

簡化結構也許又把可讀性降低了？ㄟ不管了（

**Comment by objmagic** [comment]
OCaml code:

``` ocaml
type rule = (int * string) list

let rule_a = [(3, "fjzz"); (5, "buzz"); (7, "hjss"); (11, "howl")]

let fizzbuzz n rule =
  let f = fun acc (d, s) ->
    if n mod d = 0 then (acc ^ s) else acc in
  let s = List.fold_left f "" rule in
  if s = "" then string_of_int n else s
```

**Comment by shouya** [comment]
抱歉～剛剛意識到我上面的代碼其實結果不太對，`fizzfuzz 9` 會生成 `"fizzfizz"` 而非 `"fizz"`，修正如下：

``` haskell
instance Semigroup (Int, [String]) where
  (n1,s1) <> (n2,s2) = (n1*n2, s1 `union` s2)

fizzSeq :: [(Int, [String])]
fizzSeq = (3 , ["fizz"]):(5 , ["buzz"]):(7 , ["hiss"]):(11, ["howl"]):
          [x <> y | x <- fizzSeq, y <- fizzSeq]

fizzbuzz'' n = concat $ fromMaybe [] $ lookup n fizzSeq
```

**Comment by scturtle** [comment]
@shouya 我觉得这样结果还是不大对，比如 (15,["buzz","fizz"]) 我觉得应该是 fizzbuzz。
我记得有个算法是可以不重复且有序的生成这种序列。好像是先把 3、5、7、11 建个最小堆，不断的取出最小的，乘以 3、5、7、11 再放回堆里，这样每次取出来的那个就是有序的。这样说不定可以免去查找。

**Comment by freizl** [comment]
How about this approach, base on idea present by the article.

```
module Main where

test :: Int -> String -> Int -> [String]
test x str n = [ str | n `mod` x == 0 ]

fizz :: Int -> [String]
fizz = test 3 "fizz"

buzz :: Int -> [String]
buzz = test 5 "buzz"

fz :: Int -> String
fz n = concat $ fizz n ++ buzz n

main :: IO ()
main = mapM_ print [(x, fz x) | x <- [1..20] ++ [70..80]]

```

**Comment by ninegua** [comment]
的确是个 semigroup，有一边的 identity，但基础结构不是 product，而是 sum

``` haskell
Left x ++* Left y  = Left $ x ++ y
x      ++* Right _ = x
_      ++* x       = x

toFB i = foldr1 (++*) [base i, fizz i, buzz i] 
  where 
    test n i | i `mod` n == 0 = Left 
             | otherwise      = Right
    base = Right . show 
    fizz = flip (test 3) "fizz"
    buzz = flip (test 5) "buzz"

showFB = either id id 

fizzbuzz = map (showFB . toFB)
```

可以证明 ++\* 是 associative，有多个 right identity ＝`Right x`, for all `x`。改改也可以做成满足 left identity 的。

**Comment by ninegua** [comment]
文章本身是用 continuation 来做的，鉴于 function 可以 encode both sum and product，应该可以做一些推导转化，至少可以从 sum based 转到 continuation based。文章开头用“多做一个空串匹配是多余的说法”来做 motivation，感觉不是很有说服力。

这个问题更简洁的解法是基于 Maybe 和 Monoid，其实和最后利用空串来判断并无不同:

``` haskell
{-# LANGUAGE MonadComprehensions #-}
fizzbuzz i = fromMaybe (show i) $ mappend ["fizz" | i `rem` 3 == 0]
                                          ["buzz" | i `rem` 5 == 0]
```

我的解法基于 semigroup，相当于是 对 Monoid + Maybe 做了一个 generalization，感觉有点 leaky，因为可以用 Right 来 encode 冗余的信息。所以，如果进一步 generalize 到 continuation，应该更 leaky，至少不会更有效率。当然，我没有具体证明，只是个直觉而已，欢迎继续讨论。

**Comment by Javran** [comment]
@ninegua 啊谢谢九瓜老师,这个看起来非常厉害的样子!

我其实还有一个关于SHP machine的想法但是不知道怎么验证:

能不能用Cont+Writer的方法来实现呢? 之前看了一下 [The Mother of all Monads](http://blog.sigfpe.com/2008/12/mother-of-all-monads.html) 觉着文章一开头的那个例子似乎和这里的情况很像,`SKIP`和`PRINT s`似乎都挺好实现,但是要实现`HALT`似乎要对continuation进行操作,但是我实在是不熟悉Cont Monad,不知道是否可行以及如果写起来的话会是什么样子的.

**Comment by Javran** [comment]
> 我的解法基于 semigroup，相当于是 对 Monoid + Maybe 做了一个 generalization，感觉有点 leaky，因为可以用 Right 来 encode 冗余的信息。所以，如果进一步 generalize 到 continuation，应该更 leaky，至少不会更有效率。当然，我没有具体证明，只是个直觉而已，欢迎继续讨论。

这个部分感觉看起来有点吃力:
- 这个Monoid + Maybe具体来说是不是指把 String monoid 给lift到Maybe里去然后用`""`打标记呢?
- 能否解释一下"leaky"具体指的是什么样的问题呢?

**Comment by freizl** [comment]
@ninegua @Javran 
如果用`Maybe`（理解我们其实用类型`[]`代替了文中的`Cmd`类型），那文中新定义一个的意义在于什么？

`MonadComprehensions` 很有意思，学习了. :+1: 
才发现我的实现有点问题，也要借助这个东西

**Comment by ninegua** [comment]
这个 Monoid+Maybe 的做法是：先将 `i :: Integer` 转为 `[fizz i, buzz i] :: [Maybe String]`，然后用 `mconcat` 把列表压成一个 `Maybe String`，最后使用 `fromMaybe` 来提取最终字串 (当为 `Just` )，或者使用缺省字串 (当为 `Nothing`）。注意这里有个顺序，必须是先使用 `mconcat` 然后才使用 `fromMaybe`。

我的 SemiGroup+Either 的做法是，将 `i :: Integer` 转为 `[base i, fizz i, buzz i] :: [Either String String]`，然后用 `foldr1 (++*)` 把它压成一个 `Either String String`，最后提取其中字串。可以比较一下 `[Maybe String]` 和 `[Either String String]` 这两个数据结构，显然后者可以包含更多信息，但是因为我定义的 `++*` 当第二个参数为 `Right` 时会完全忽略掉它，所以只有当列表里第一个数据为 `Right` 才有可能把其内嵌的值传递到最终值里面去。 这就时为什么 `base i` 要写在最前面。尽管最终计算结果都是一样的，但是因为中间使用的数据结构可以包含更多信息，所以我说有些 leaky。而且可以完全定义一个对称的 `*++` 操作，这样用的时候需要把 `base i` 放在最后，就和 Monoid+Maybe 的做法更接近了。当然，用 semigroup 呢，从理论上显得更统一些，因为它把必须放在最后的 `fromMaybe` 操作 generalize 到 Monoid 元素之间的操作，让 `<>` 变成了 `(++*)`，而代价是，失去了一边的 identity 性质。

这也是为什么我认为，原文使用 continuation 实际上是用了一种更 general 的数据结构（就是函数啦）来 encode 一个 semigroup，其实更为 leaky。

当然，使用 leaky 的中间表现形式，并不总意味着需要付出额外的计算代价。首先我们必须要定义清楚什么是“代价”，深究下去就比较复杂了，这也是为什么我觉得原文的 motivation 不够有说服力。

**Comment by ninegua** [comment]
@Javran 用 continuation monad (callCC) 主要是为了得到 current continuation，这个问题里面感觉不是为了得到 current continuation 来改变 control flow，所以我猜想帮助不大。如果你有兴趣，也可以试试。

**Comment by Javran** [comment]
关闭旧issue
