### ISSUE TITLE
小組線上討論第二彈！

### ISSUE THREAD

**Issue by shouya** [CNMDR3G/CNMDR3G#5]
首先感謝大家於上週（三月十七日）在 IRC 上進行了活躍的討論，關於內容可以見於 https://github.com/CNMDR3G/CNMDR3G/issues/3 裡 Javran 紀錄的 irc log。

我們這次的 topic 是 Practical Type System Benefits（[PDF](https://themonadreader.files.wordpress.com/2014/04/nccb.pdf)），如果沒有異議的話討論會繼續在 IRC 的 `#haskell-cn` 頻道上進行。就像上次一樣，請大家先 [在此](http://www.when2meet.com/?2860186-XGKd1) 填一下自己方便參加討論的時間，我們會找個大部份人都有空的時間進行這次討論。

填表方法：your name 里填上名字, sign in 之后把自己方便的时间涂绿即可（**請以北京時間為準**）。如果填入相同的用户名是可以修改自己的时间的，所以不一定要完全确定了再填表。

同時也歡迎大家在 issue 裡討論分享自己的想法，總之大白兔希望大家踴躍參與～

**Comment by shouya** [comment]
根據上面收集到的大家空閒時間的信息，看來三月二十七日比較適合。那麼我們就把這次討論定在**北京時間** **三月二十七日 10:30 至 14:00**。參與討論不需要註冊或預先聲明，在討論期間任何人都可以直接加入 IRC chat.freenode.net 服務器的 `#haskell-cn` 頻道參與這次討論。（沒有 IRC 客戶端的同學也可以點擊 [此鏈接](http://webchat.freenode.net/?channels=#haskell-cn) 進入網頁版聊天室）

如果錯過了這次線上討論也沒關係，我會盡可能把討論內容（irc log）紀錄並在討論結束發佈。當然其他時間大家也可以在這個 repository 的 issue 上發帖或加入 `#haskell-cn` 一起玩。最後謝謝大家，大白兔祝大家玩得愉快！

**Comment by shouya** [comment]
我剛剛在 Google Calendar 上建立了小組活動日程的行事曆，如果有使用 Google Calendar 的同學就不需要自己手動創建事項了。

訂閱 CNMDR3G 小組活動日程：
[HTML](https://www.google.com/calendar/embed?src=tqm2vj2iltsei68cn6bucq6k68%40group.calendar.google.com) ‧ [ICAL](https://www.google.com/calendar/ical/tqm2vj2iltsei68cn6bucq6k68%40group.calendar.google.com/public/basic.ics) ‧ [XML](https://www.google.com/calendar/feeds/tqm2vj2iltsei68cn6bucq6k68%40group.calendar.google.com/public/basic)

**Comment by shouya** [comment]
這次討論的 IRC 日誌見：
https://gist.github.com/shouya/c89f22c52963430b9b95

謝謝大家的熱情參與！下次討論的主題是 Supercompilation～ （[見此 Issue](https://github.com/CNMDR3G/CNMDR3G/issues/1#issuecomment-77630070)）

**Comment by Javran** [comment]
感谢大家对这两次讨论的参与.

接下来讨论的文章将是Supercompilation,由于文章内容似乎比较多,我们考虑分成多次讨论.

这段时间请大家不用担心阅读的进度问题,届时将开新的issue商量下次会讨论的部分.

cmV2ZXJzZSAobWFwIChzdWNjIC4gc3VjYykgIixzbXdcUlNmcmd1XFJTY2BcUlN3bGxzYFxSU3Js
X2dlXFJTY2ZyXFJTd19LIikK

**Comment by Javran** [comment]
关闭过期issue.
