### ISSUE TITLE
第四次小组线上讨论 

### ISSUE THREAD

**Issue by Javran** [CNMDR3G/CNMDR3G#7]
暂定在4月15日到5月2日中的某一天(注意时间一律以北京时间为准).

和以前一样,讨论的具体时间取决于大部分人方便参与的时间,因此请大家参与填写 [when2meet](http://www.when2meet.com/?2979806-r4DKd) 上的表格,若不清楚如何操作请阅读本文.

届时将以 freenode 上的 `#haskell-cn` 频道作为讨论平台,关于如何参与讨论,具体事项参见[链接](https://github.com/CNMDR3G/CNMDR3G/wiki#%E5%A6%82%E4%BD%95%E5%8F%82%E4%B8%8E).

本次讨论的话题将是Issue 23中的[Supercompilation](https://themonadreader.files.wordpress.com/2014/04/super-final.pdf). 由于文章的内容比较多,大家量力而行.

我们将分多次进行线上聚会讨论,请在本issue下方留言,商量决定下次讨论的部分.

上次讨论到的部分大概是在`An Overview of SC Mini`之前的那部分,主要是关于名词概念的理解分享.详情请[参见聊天记录](https://gist.github.com/Javran/dc4b1831cd79a8282e3c) 近期若有时间,我会新开个issue把上次讨论的东西汇总一下,届时欢迎大家补充.

上次聚会是我组织上的失误,通知太迟了,给大家道个歉.以后我尽量保证在聚会的前两三天(至少早于24小时)发布通知.请大家关注.

有任何不明白的地方可以在本issue留言或者直接给我发邮件(github profile上应该有地址).

**Comment by Javran** [comment]
似乎这周没什么人参与的样子,征集个意见: 我们这周是搞个非正式的大家随意聊聊等更多人参与进来,还是加速一下把supercompliation的话题先讨论完?

因为不太清楚大家是觉得对这个话题不感兴趣/太长了懒得读/看不懂讨论的内容还是别的什么的.

大家畅所欲言.不方便的话微博上给我私信什么的都可以.

**Comment by luochen1990** [comment]
支持先随意聊聊，搞得太正式反而让大家觉得心理压力大都不敢参加了。

**Comment by Javran** [comment]
@luochen1990 吼啊,有道理,原本的目的就是希望大家都参与进来的.就我们几个人在聊的话那其实效果不算太好吧..

**Comment by ninegua** [comment]
什么形式都尽量参加！

**Comment by Javran** [comment]
@ninegua 谢谢兹磁!

另刚才和推上的同学们交流了一下,感觉大家没多少兴趣读太长的东西,
再花几个星期去看的话似乎也有悖这个小组的目的.

目前的想法:
- 把supercompliation快进掉,剩下没讨论的部分大家能消化多少就消化多少,然后下周换到Issue 22话题的讨论.
- 希望有更多的同学能参与讨论,因此supercompliation不会占本周讨论的大部分时间.
- 请新人积极提问,再简单的问题都没有关系,讨论组应该是偏向搞科普性质的因此大家的反馈是很重要的!

大家觉得这样如何?

**Comment by Javran** [comment]
ok那就先这样定了: 北京时间4月18日上午10:00-13:00. 计划是supercompilation的内容稍微过一下,然后剩两个小时非正式的大家随意聊聊,欢迎大家踊跃参与!

**Comment by Javran** [comment]
reminder. 下一个整点开始,不过对supercompliation没兴趣的话可以11点再来!

**Comment by Javran** [comment]
感谢大家的参加!
第四次线上讨论的聊天记录: [链接](https://gist.github.com/Javran/de83dd8d670573f2045a)

**Comment by Javran** [comment]
过期话题关闭
