### ISSUE TITLE
 话题调查

### ISSUE THREAD

**Issue by Javran** [CNMDR3G/CNMDR3G#9]
感觉从第一次话题开始至今有些时候了,感谢这段时间里大家的参与和支持!

这次是关于接下来的话题的调查: Issue 23还有两篇,然后就是Issue 22新的三篇

讨论顺序按这次调查的票数决定,issue 23和issue 22独立排序.

截止日期我就不设置了,大概下周这时间我会看一下投票的结果.

(所以下周若有线上讨论的话应该是自由话题)

请大家点击链接参与:  [链接](https://www.surveymonkey.com/s/WQTPJYL), 一共两个问题,五个选项,大家把自己感兴趣的选择一下提交就可以了.因为是匿名的调查,故请避免重复提交.

这次试一试用SurveyMonkey,墙内要是不能用的话请在回复里告知一下.

**Comment by Javran** [comment]
附上Editorial的摘要供大家参考:

# Issue 23
-   In a break from the usual uses of Haskell, Henrik, Daniel and Mikael
  describe **Haskell sound specification DSL** used in service of a
  live action role-playing game situated in the Battlestar Galactica
  universe.
-   Alberto talks about his web framework, **MFlow**, which provides a
  continuation-like method of structuring web applications, without
  actually opening the can of worms that is explicitly serializing
  continuations.

# Issue 22
- **Generalized Algebraic Data Types in Haskell** is an in-depth tutorial about generalized algebraic data types, covering all of the classic use-cases of this useful type system extension. 
- **Error Reporting Parsers: a Monad Transformer Approach** is a meditation on the design pattern of monad transformers, and how they can help the develop the design of a parser library. 
- **Two Monoids for Approximating NP-Complete Problems** shows how even a simple API like that of a monoid can help code achieve dramatic speed-ups.

**Comment by fishtreesugar** [comment]
issue 22第三个editorial 搞错了?

**Comment by ninegua** [comment]
MFlow +1. 这种将 client 和 server 结合在一起写 App 的方式绝对是一大进步，值得学习。

**Comment by Javran** [comment]
@fishtreesugar  谢谢,已修正.

**Comment by Javran** [comment]
在此发一下话题调查的[结果链接](https://www.surveymonkey.com/results/SM-FKSXNZQ9/),
感觉基本就是这个样子了不过我将继续开放调查.

**Comment by Javran** [comment]
过期话题关闭.
